# Generated by Django 4.0.6 on 2022-08-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_newuser_first_name_alter_newuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Прізвище'),
        ),
    ]
