# Generated by Django 4.0.6 on 2022-08-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_remove_comment_article_article_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments',
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='article_comments', to='newsapp.comment'),
        ),
    ]
