# Generated by Django 4.0.6 on 2022-08-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_remove_article_comments_article_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
