# Generated by Django 3.2.14 on 2022-07-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_alter_comment_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='article_comments', to='newsapp.Comment'),
        ),
    ]
