# Generated by Django 4.0.6 on 2022-08-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, related_name='article_comments', to='newsapp.comment'),
        ),
    ]
